keybindings:
  HomeScreen:
    up: Up
    down: Down
    enter: Confirm
    esc: Cancel
    h: Help
    i: Insert
    q: Quit
  Editor:
    up: Up
    down: Down
    left: Left
    right: Right
    shift-up: SelectUp
    shift-down: SelectDown
    shift-left: SelectLeft
    shift-right: SelectRight
    backspace: Backspace
    delete: Delete
    tab: Tab
    enter: NewLine
    esc: Cancel
    ctrl-h: Help
    ctrl-i: Insert
    ctrl-q: Quit
    ctrl-s: Save
    ctrl-a: SelectAll
    ctrl-x: Cut
    ctrl-c: Copy
    ctrl-v: Paste
    ctrl-e: Return
    ctrl-z: Undo
    ctrl-shift-z: Redo
    ctrl-p: OpenFile
    ctrl-f: Search
    alt-up: PageUp
    pageup: PageUp
    alt-down: PageDown
    pagedown: PageDown
    alt-left: StartOfWord
    alt-right: EndOfWord
  FileDialog:
    up: Up
    down: Down
    left: Left
    right: Right
    enter: Confirm
    ctrl-f: Search
    ctrl-enter: Select
    ctrl-v: Paste
    backspace: Backspace
    delete: Delete
    esc: Cancel
    ctrl-p: TogglePreview
    ctrl-r: ReloadPreview

appconfig:
