keybindings:
  HomeScreen:
    up: Up
    down: Down
    enter: Confirm
    esc: Cancel
    q: Quit
    h: ToggleHelp
  Dialog:
    esc: Cancel
    enter: Confirm
  Editor:
    up: Up
    down: Down
    left: Left
    right: Right
    shift-up: SelectUp
    shift-down: SelectDown
    shift-left: SelectLeft
    shift-right: SelectRight
    backspace: Backspace
    delete: Delete
    tab: Tab
    enter: NewLine
    esc: Cancel
    ctrl-h: ToggleHelp
    ctrl-i: Insert
    ctrl-q: Quit
    ctrl-s: Save
    ctrl-t: SaveTo
    ctrl-a: SelectAll
    ctrl-x: Cut
    ctrl-c: Copy
    ctrl-v: Paste
    ctrl-w: Return
    ctrl-z: Undo
    ctrl-r: Redo
    ctrl-o: OpenFile
    ctrl-f: Search
    ctrl-l: ToggleLineNumber
    ctrl-y: ToggleSearchRegex
    alt-up: PageUp
    pageup: PageUp
    alt-down: PageDown
    pagedown: PageDown
    alt-left: StartOfWord
    alt-right: EndOfWord
  FileDialog:
    up: Up
    down: Down
    left: Left
    right: Right
    enter: Confirm
    ctrl-f: Search
    ctrl-enter: Select
    ctrl-v: Paste
    backspace: Backspace
    delete: Delete
    esc: Cancel
    ctrl-p: TogglePreview
    ctrl-r: ReloadPreview

appconfig:
